spring.application.name=mockmate-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/mockmate
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:1Praveen@}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
server.port=8080
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=604800000
app.jwt.refresh-expiration-ms=2592000000
app.gemini.api-key=${GEMINI_API_KEY}
app.gemini.model=gemini-2.5-flash
app.upload.dir=${UPLOAD_DIR:./uploads}
app.cors.allowed-origins=${CORS_ORIGINS:http://localhost:5173}
management.endpoints.web.exposure.include=health,info
logging.level.com.mockmate=DEBUG
logging.level.org.springframework.security=INFO
